name: CI/CD Pipeline with Era Test Node

on:
  push:
    branches:
      - main  # Cambia a la rama que desees (main, master, etc.)

jobs:
  test:
    name: Run Era Test Node and Tests
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Ejecutar Era Test Node
      - name: Run Era Test Node
        uses: dutterbutter/era-test-node-action@latest
        with:
          mode: 'run'  # Modo de ejecución
          showCalls: 'user'  # Mostrar llamadas de usuario
          showStorageLogs: 'read'  # Mostrar logs de almacenamiento
          showVmDetails: 'all'  # Mostrar detalles de la VM
          showGasDetails: 'all'  # Mostrar detalles de gas
          resolveHashes: 'true'  # Habilitar resolución de hashes
          log: 'info'  # Nivel de logs
          logFilePath: 'era_test_node.log'  # Ruta del archivo de logs
          target: 'x86_64-unknown-linux-gnu'  # Arquitectura objetivo
          releaseTag: 'latest'  # Versión de era_test_node

      # Paso 3: Instalar dependencias (si es necesario)
      - name: Install dependencies
        run: npm install  # Cambia este comando según tu proyecto

      # Paso 4: Ejecutar pruebas
      - name: Run tests
        run: npm test  # Cambia este comando según tu proyecto

      # Paso 5: Subir logs como artefactos (opcional)
      - name: Upload era_test_node log
        uses: actions/upload-artifact@v3
        with:
          name: era_test_node-log
          path: era_test_node.log

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test  # Depende del job "test"
    if: success()  # Solo se ejecuta si el job "test" pasa

    steps:
      # Paso 1: Obtener el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js (si tu proyecto lo requiere)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # Cambia a la versión de Node.js que uses

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Construir el proyecto
      - name: Build project
        run: npm run build  # Cambia este comando según tu proyecto

      # Paso 5: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token de GitHub
          publish_dir: ./dist  # Cambia "dist" por la carpeta de tu build