name: CI/CD Pipeline with Era Test Node

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Era Test Node and Tests
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el c칩digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar dependencias del sistema (si es necesario)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev

      # Paso 3: Ejecutar Era Test Node con el puerto 4321
      - name: Run Era Test Node
        id: era_test_node
        uses: dutterbutter/era-test-node-action@latest
        with:
          mode: 'run'
          port: '4321'  # Usamos el puerto 4321
          showCalls: 'user'
          showStorageLogs: 'read'
          showVmDetails: 'all'
          showGasDetails: 'all'
          resolveHashes: 'true'
          log: 'debug'  # Cambiamos a 'debug' para m치s detalles
          logFilePath: 'era_test_node.log'
          target: 'x86_64-unknown-linux-gnu'
          releaseTag: 'latest'

      # Paso 4: Verificar si el Era Test Node se est치 ejecutando
      - name: Check Era Test Node status
        run: |
          if [ -f era_test_node.log ]; then
            echo "Era Test Node log:"
            cat era_test_node.log
          else
            echo "No log file found."
          fi

      # Paso 5: Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # Paso 6: Ejecutar pruebas
      - name: Run tests
        run: npm test

      # Paso 7: Subir logs como artefactos (opcional)
      - name: Upload era_test_node log
        uses: actions/upload-artifact@v3
        with:
          name: era_test_node-log
          path: era_test_node.log

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      # Paso 1: Obtener el c칩digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Construir el proyecto
      - name: Build project
        run: npm run build

      # Paso 5: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
